-- MySQL Script generated by MySQL Workbench
-- Sat May 25 22:43:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbVendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbVendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbVendas` DEFAULT CHARACTER SET utf8 ;
USE `dbVendas` ;

-- -----------------------------------------------------
-- Table `dbVendas`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVendas`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  `Foto` LONGBLOB NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbVendas`.`OrdemDeServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbVendas`.`OrdemDeServico` (
  `idOrdemDeServico` INT NOT NULL,
  `TipoDeServico` LONGTEXT NULL,
  `ValorServico` DOUBLE NULL,
  `DataDeEntrega` VARCHAR(45) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idOrdemDeServico`),
  INDEX `fk_OrdemDeServico_Usuarios_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemDeServico_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `dbVendas`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
